name: Fetch Icon Folders Monthly

on:
  schedule:
    - cron: "0 0 1 * *"  # Run at midnight on the 1st day of each month
  workflow_dispatch:  # Allow manual triggers

jobs:
  fetch-icons:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up directories
        run: mkdir -p icons

      - name: Clone nvstly repository with sparse checkout
        run: |
          git clone --depth 1 --filter=blob:none --sparse https://github.com/nvstly/icons.git temp_icons
          cd temp_icons
          git sparse-checkout set crypto_icons exchange_icons forex_icons ticker_icons
          mv crypto_icons ../icons/crypto_icons
          mv exchange_icons ../icons/exchange_icons
          mv forex_icons ../icons/forex_icons
          mv ticker_icons ../icons/ticker_icons
          cd ..
          rm -rf temp_icons

      - name: Clone ahmeterenodaci repository and process icons
        run: |
          # Clone the ahmeterenodaci repository
          git clone --depth 1 https://github.com/ahmeterenodaci/Nasdaq-Stock-Exchange-including-Symbols-and-Logos.git temp_nasdaq
          
          # Create destination directories
          mkdir -p icons/stock_icons
          mkdir -p temp_processing
          
          # Process the logo files - remove underscores and check for duplicates
          cd temp_nasdaq/logos
          
          for file in *; do
            if [ -f "$file" ]; then
              # Remove underscore from filename
              new_name=$(echo "$file" | sed 's/^_//')
              
              # Check if the file already exists in our icons directory
              if [ ! -f "../../../icons/stock_icons/$new_name" ]; then
                # File doesn't exist in destination, copy it
                cp "$file" "../../../temp_processing/$new_name"
              else
                echo "Skipping duplicate file: $new_name"
              fi
            fi
          done
          
          # Move the processed files to the final destination
          cd ../../../
          cp -r temp_processing/* icons/stock_icons/ 2>/dev/null || true
          
          # Clean up temporary directories
          rm -rf temp_nasdaq
          rm -rf temp_processing

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add icons/
          git diff --staged --quiet || git commit -m "Update icon folders (monthly fetch)"
          git push || echo "No changes to push"
