name: Fetch Icon Folders Monthly

on:
  schedule:
    - cron: "0 0 1 * *"  # Run at midnight on the 1st day of each month
  workflow_dispatch:  # Allow manual triggers

jobs:
  fetch-icons:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up directories
        run: |
          # Create stock_icons directory
          mkdir -p ${GITHUB_WORKSPACE}/icons/stock_icons

      - name: Clone nvstly repository with sparse checkout
        run: |
          git clone --depth 1 --filter=blob:none --sparse https://github.com/nvstly/icons.git ${GITHUB_WORKSPACE}/temp_icons
          cd ${GITHUB_WORKSPACE}/temp_icons
          git sparse-checkout set crypto_icons exchange_icons forex_icons ticker_icons
          
          # Copy all icons from different categories directly into stock_icons
          find ${GITHUB_WORKSPACE}/temp_icons/crypto_icons -type f -name "*.png" -o -name "*.jpg" -o -name "*.svg" | while read file; do
            filename=$(basename "$file")
            cp "$file" "${GITHUB_WORKSPACE}/icons/stock_icons/$filename" || true
          done
          
          find ${GITHUB_WORKSPACE}/temp_icons/exchange_icons -type f -name "*.png" -o -name "*.jpg" -o -name "*.svg" | while read file; do
            filename=$(basename "$file")
            cp "$file" "${GITHUB_WORKSPACE}/icons/stock_icons/$filename" || true
          done
          
          find ${GITHUB_WORKSPACE}/temp_icons/forex_icons -type f -name "*.png" -o -name "*.jpg" -o -name "*.svg" | while read file; do
            filename=$(basename "$file")
            cp "$file" "${GITHUB_WORKSPACE}/icons/stock_icons/$filename" || true
          done
          
          find ${GITHUB_WORKSPACE}/temp_icons/ticker_icons -type f -name "*.png" -o -name "*.jpg" -o -name "*.svg" | while read file; do
            filename=$(basename "$file")
            cp "$file" "${GITHUB_WORKSPACE}/icons/stock_icons/$filename" || true
          done
          
          # Clean up
          rm -rf ${GITHUB_WORKSPACE}/temp_icons

      - name: Clone ahmeterenodaci repository and process icons
        run: |
          # Clone the repository
          git clone --depth 1 https://github.com/ahmeterenodaci/Nasdaq-Stock-Exchange-including-Symbols-and-Logos.git ${GITHUB_WORKSPACE}/temp_nasdaq
          
          # Process each file individually with absolute paths
          find ${GITHUB_WORKSPACE}/temp_nasdaq/logos -type f -name "*.png" -o -name "*.jpg" -o -name "*.svg" | while read file; do
            filename=$(basename "$file")
            # Remove leading underscore if present
            new_filename=$(echo "$filename" | sed 's/^_//')
            
            # Check if file already exists in destination
            if [ ! -f "${GITHUB_WORKSPACE}/icons/stock_icons/$new_filename" ]; then
              echo "Copying $filename as $new_filename"
              cp "$file" "${GITHUB_WORKSPACE}/icons/stock_icons/$new_filename"
            else
              echo "Skipping duplicate: $new_filename"
            fi
          done
          
          # Clean up
          rm -rf ${GITHUB_WORKSPACE}/temp_nasdaq

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add icons/
          git diff --staged --quiet || git commit -m "Update consolidated icon folders (monthly fetch)"
          git push || echo "No changes to push"
